version: "3.8"
services:
  app:
    container_name: next-app
    build:
      context: .
      target: $DOCKER_NODE_ENV
    restart: always
    # command: tail -f /dev/null
    env_file: .env
    # volumes:
    # - .:/app
    # - /app/node_modules
    # - /app/.next
    ports:
      - $SERVER_PORT:$SERVER_PORT
