version: "3.8"
services:
  app:
    container_name: next-app
    build:
      context: .
      target: dev
    restart: always
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - $SERVER_PORT:$SERVER_PORT
